[package]
name = "deaddrop-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true
description = "Stable DeadDrop application SDK"
readme = "../../README.md"
documentation = "https://docs.rs/deaddrop-sdk"

[dependencies]
deaddrop-core.workspace = true
deaddrop-net.workspace = true

[lints]
workspace = true
